"use client";
import { AnimatePresence, motion } from "framer-motion";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { projects } from "@/lib/content";
import type { Project } from "@/types/content";
const filters = ["todos", "web", "app", "landing", "ecommerce"] as const;
export function ProjectsGrid({ items = projects, language = "es" }: { items?: Project[]; language?: "es" | "en" }) { const path = usePathname(); const locale = language === "en" || path.startsWith("/en") ? "en" : "es"; const [filter, setFilter] = useState<(typeof filters)[number]>("todos"); const visible = items.filter((p) => filter === "todos" || p.category === filter); const text = locale === "en" ? { all: "all", view: "View project" } : { all: "todos", view: "Ver proyecto" }; return <><div className="mb-8 flex flex-wrap gap-2">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-4 py-2 text-sm capitalize transition ${filter === item ? "bg-white text-zinc-950" : "bg-white/10 hover:bg-white/20"}`}>{item === "todos" ? text.all : item}</button>)}</div><motion.div layout className="grid gap-4 md:grid-cols-3"><AnimatePresence mode="popLayout">{visible.map((project, index) => <motion.article layout key={project.id} initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .96 }} whileHover={{ y: -7 }} className={`overflow-hidden rounded-3xl text-zinc-950 ${index === 0 ? "bg-lime-300" : index === 1 ? "bg-orange-200" : "bg-sky-200"}`}><Link href={`${locale === "en" ? "/en" : ""}/proyectos/${project.slug}`} className="block min-h-72 p-6" style={project.coverImage ? { backgroundImage: `linear-gradient(180deg, transparent 25%, rgba(0,0,0,.2)), url(${project.coverImage})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined}><p className={`text-sm uppercase tracking-widest ${project.coverImage ? "text-white" : "text-black/55"}`}>{project.category}</p><div className="mt-24"><h3 className={`text-2xl font-bold ${project.coverImage ? "text-white" : ""}`}>{project.title}</h3><p className={`mt-2 max-w-xs ${project.coverImage ? "text-white/90" : "text-black/70"}`}>{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.technologies.map((tech) => <span key={tech} className={`rounded-full border px-2 py-1 text-xs ${project.coverImage ? "border-white/40 text-white" : "border-black/15"}`}>{tech}</span>)}</div><span className={`mt-5 inline-block text-sm font-bold ${project.coverImage ? "text-white" : ""}`}>{text.view} →</span></div></Link></motion.article>)}</AnimatePresence></motion.div></>; }
